# deploy the container with the image 'mc'
# using -p 25565:25565 and bind /world as a volume to /app/world in the container
# run with options -it and execute java -jar server.jar

services:
  mc:
    image: mc
    ports:
      - "25565:25565"
    volumes:
      - /home/ec2-user/world/:/app/world
      - /home/ec2-user/plugins-config/Passky/passwords.yml:/app/plugins/Passky/passwords.yml
    stdin_open: true
    tty: true
    command: java -jar server.jar