# deploy the container with the image 'mc'
# using -p 25565:25565 and bind /world as a volume to /app/world in the container
# run with options -it and execute java -jar server.jar

services:
  mc:
    image: mc
    ports:
      - "25565:25565"
    volumes:
      - ./world:/app/world
    tty: true
    command: java -jar server.jar