services:
  mc-server:
    image: mc
    ports:
      - 25565:25565
    volumes:
      - ./world:/world
    environment:
      EULA: "true"
    stdin_open: true
    tty: true

volumes:
  world:
    driver: local
