name: Build terraform IaC

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'

env:
  TF_LOG: INFO
  TF_WORKING_DIR: terraform/
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_WORKING_DIR }}

  steps:
    - name: Checkout the repository to the runner
      uses: actions/checkout@v4

    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.9.3

    - name: Terraform init
      id: init
      run: terraform init -backend-config="bucket=terraform-state-logs"

    - name: Terraform plan
      id: plan
      run: |
        terraform plan -input=false -out=tfplan \
        && terraform show -no-color tfplan

    - name: Terraform Apply
      if: ${{ github.ref == 'refs/heads/main' }}
      run: terraform apply -auto-approve
